=begin
#Gomematic OpenAPI

#API definition for Gomematic

The version of the OpenAPI document: 1.0.0-alpha1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

module Gomematic
  VERSION = '1.0.0-alpha1'
end
